Metamorph provision support
RHQE/metamorph pull request #11
Opened 2017-04-23 23:22 UTC by Jurisak

This commit is initial implementation. It will be extended.

+ Included intial tests
- without documentation

2017-05-02 17:52 UTC, robnester-rh reviewed
I would suggest looking at cases where you're opening paths to read or write from and consider wrapping them with a try, in case the path doesn't exist.

2017-05-02 17:52 UTC, robnester-rh commented on .travis.yml
> +  - pip install PyYaml
I'd suggest using a requirements.txt file containing the requirements.

2017-05-02 17:52 UTC, robnester-rh commented on docs/source/index.rst
> +Provision plugin purpose is to create topology files. These files will be handled by linch pin tool.
Reword to:
The purpose of the provision plugin is to create topology files.

2017-05-02 17:52 UTC, robnester-rh commented on docs/source/index.rst
> +This plugin created two files:
nit: correct to creates

2017-05-02 17:52 UTC, robnester-rh commented on metamorph/plugins/morph_provision.py
> +        with open(osp_config_path) as osp_config:
I'd wrap this in a try to ensure the path exists.

2017-05-02 17:52 UTC, robnester-rh commented on metamorph/plugins/morph_provision.py
> +        with open(metadata_path) as metadata_fp:
Wrap in a try to ensure the path exists.

2017-05-02 17:52 UTC, robnester-rh commented on metamorph/plugins/morph_provision.py
> +        if type(metadata_source) is list:
Just a note:
Generally speaking, I think it's more pythonic to employ duck typing and do something like:
```
if isinstance(metadata_source, list):
```

2017-05-02 17:52 UTC, robnester-rh commented on metamorph/plugins/morph_provision.py
> +            git_repo = git_repo[:-1]
easier just to do:
```
git_repo = git_repo.rstrip('/')
```
If git_repo ends with '/' it'll strip it. If it doesn't end with '/' git_repo will be unaffected.

2017-05-02 17:52 UTC, robnester-rh commented on metamorph/plugins/morph_provision.py
> +        return splitted_repo_path[-1].split('.')[0]
this whole method could be rewritten as:

```
return git_repo.rstrip('/').split('/')[-1].split('.')[0]
```

2017-05-02 17:52 UTC, robnester-rh commented on metamorph/plugins/morph_provision.py
> +def write_results(destination, results, json_type=True):
Wrap in a try in case the destination doesn't exist.

2017-05-03 09:11 UTC, gsr-shanks commented
Please resolve conflicts and implement review comments.

2017-05-05 11:41 UTC, Jurisak commented on docs/source/index.rst
> +This plugin created two files:
thanks

2017-05-05 11:42 UTC, Jurisak commented on metamorph/plugins/morph_provision.py
> +        with open(osp_config_path) as osp_config:
yes :)

2017-05-05 11:52 UTC, Jurisak commented on metamorph/plugins/morph_provision.py
> +        with open(metadata_path) as metadata_fp:
ok

2017-05-05 11:54 UTC, Jurisak commented on metamorph/plugins/morph_provision.py
> +        if type(metadata_source) is list:
looks better ;) thanks

2017-05-05 11:56 UTC, Jurisak commented on metamorph/plugins/morph_provision.py
> +            git_repo = git_repo[:-1]
I did not know about it. Thanks.

2017-05-05 11:57 UTC, Jurisak commented on metamorph/plugins/morph_provision.py
> +        return splitted_repo_path[-1].split('.')[0]
Yes but I like my version more.

2017-05-05 12:01 UTC, Jurisak commented on metamorph/plugins/morph_provision.py
> +def write_results(destination, results, json_type=True):
sure

2017-05-13 08:10 UTC, gsr-shanks commented
Please resolve conflicts

2017-05-13 08:20 UTC, Jurisak commented
I don't have time to do it today, but I'll be able to do it tomorrow.

2017-05-15 11:55 UTC, Jurisak commented
@gsr-shanks It can be merged now.

2017-05-16 14:57 UTC, gsr-shanks commented
@Jurisak are we blocked on https://github.com/CentOS-PaaS-SIG/linch-pin/issues/76 for this to work ?

2017-05-17 12:10 UTC, Jurisak commented
@gsr-shanks Yes, it would need a little change. Expect the patch today.

2017-05-22 12:12 UTC, Jurisak commented
@gsr-shanks @robnester-rh @Lorquas Guys, how do you see it with merging this PR?

2017-05-22 13:48 UTC, Lorquas requested changes
@Jurisak as always, code looks great

Few small nitpicks, and the docs looks it has repeated everything twice.  Looks good to me after these changes.

2017-05-22 13:48 UTC, Lorquas commented on .travis.yml
> +  - python setup.py install
don't need the extra space

2017-05-22 13:48 UTC, Lorquas commented on docs/source/index.rst
> +Provision plugin purpose is to create topology files. These files will be handled by linch pin tool.
```
The provision plugin's purpose is to create topology files. These files will be handled by the [linch pin](https://github.com/CentOS-PaaS-SIG/linch-pin) tool.  
```

2017-05-22 13:48 UTC, Lorquas commented on docs/source/index.rst
> +These two files are created from openstack config file.
```
These two files are created from an opestack config file.
```
also might need to link to an openstack config url or something showing what that is.

2017-05-22 13:48 UTC, Lorquas commented on docs/source/index.rst
> +Provision plugin provides possibility to update topology values from metadata file and metadata location dictionary
~~possibility~~  >>  the ability

~~from metadata file and~~ >> from the metadata file and the

2017-05-22 13:48 UTC, Lorquas commented on docs/source/index.rst
> +Provision
I would check this entire file, it seems to contain the same information twice!

2017-05-22 13:48 UTC, Lorquas commented on setup.py
> +    description='Exhibiting structural change of test metadata.', requires=['ansible', 'requests', 'GitPython']
the description and requires can be on separate lines

2017-05-22 20:09 UTC, Jurisak commented on .travis.yml
> +  - python setup.py install
thanks

2017-05-22 20:31 UTC, Jurisak commented
@Lorquas  How do you see it now?

2017-05-23 15:12 UTC, merged

2018-02-13 14:13 UTC, spbirhade reviewed
Looks ok